enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  1e4821c1-4244-4a2d-a256-88b138ddbd61: # Test App
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
